# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 16:12
from __future__ import unicode_literals

import NPFinal.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_tag', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Favor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('like', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=200)),
                ('hash_tag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=100, validators=[NPFinal.forms.Reg.valid_mail])),
                ('name', models.CharField(max_length=50, validators=[NPFinal.forms.Reg.valid_name])),
                ('password', models.CharField(max_length=50, validators=[NPFinal.forms.Reg.valid_pwd])),
            ],
        ),
    ]
